title: 'Текстовая страница'
extends: page-options/standard
tabs:
  content:
    label: Страница
    icon: text
    sections:
      text:
        type: fields
        fields:
          text_heading_ui:
            type: headline
            label: 'Текст страницы'
          text:
            extends: fields/rich-text
            size: huge
            label: 'Основной текст'
      child_pages:
        type: pages
        label: 'Вложенные страницы'
        templates:
          - default
        status: all
        help: 'Вложенные страницы доступны по своему адресу. Ссылки на них добавляются в текст вручную.'
  files: tabs/files
  seo: tabs/seo
