import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn, execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const { chromium } = await import(process.env.STUDIO_PLAYWRIGHT_MODULE || 'playwright');
const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const temporary = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), 'studio-seo-panel-'));
const env = { ...process.env, STUDIO_SEO_TEST_ROOT: temporary };
const port = Number(process.env.STUDIO_SEO_TEST_PORT || 8018);
const origin = `http://127.0.0.1:${port}`;
let server;
let browser;
let editorPage;
let serverOutput = '';
const errors = [];
try {
    execFileSync('php', ['tests/seo-panel-router.php'], { cwd: root, env });
    server = spawn('php', ['-S', `127.0.0.1:${port}`, 'tests/seo-panel-router.php'], { cwd: root, env });
    server.stderr.on('data', (data) => { serverOutput += data.toString(); });
    for (let attempt = 0; attempt < 50; attempt++) {
        if (server.exitCode !== null) throw new Error(serverOutput);
        try { await fetch(`${origin}/panel/login`); break; } catch {}
        await new Promise((resolve) => setTimeout(resolve, 100));
    }
    browser = await chromium.launch({ headless: true, ...(process.env.STUDIO_CHROMIUM ? { executablePath: process.env.STUDIO_CHROMIUM } : {}) });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
    editorPage = page;
    page.on('pageerror', (error) => errors.push(error.message));
    page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });
    await page.goto(`${origin}/panel/login`);
    await page.locator('input[type=email]').fill('seo-editor@example.test');
    await page.locator('input[type=password]').fill('local-seo-fixture-password');
    await page.locator('button[type=submit]').click();
    await page.waitForURL('**/panel/site');
    const field = (name) => page.locator(`.k-field-name-${name}`);
    const textField = (name) => field(name).locator('input, textarea').first();
    const imageMode = () => field('seo_image_mode').locator('select');
    const save = async () => {
        await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
        await page.waitForFunction(() => !window.panel.content.hasDiff());
    };
    const cardReady = () => page.waitForFunction(() => {
        const image = document.querySelector('.studio-social-card img');
        return image?.complete && image.naturalWidth > 0 && document.querySelector('.studio-social-card')?.getAttribute('aria-busy') === 'false';
    });
    await page.goto(`${origin}/panel/pages/fabrics+aster-cucine+atelier?tab=seo`);
    await cardReady();
    await imageMode().selectOption('shared');
    await cardReady();
    assert.match(await page.locator('.studio-social-card img').getAttribute('src'), /og-image_OG%20Fallback\.jpg$/);
    assert(!(await textField('seo_og_title').isVisible()), 'Shared mode hides cover text');
    assert(!(await field('seo_image').isVisible()), 'Shared mode hides custom image picker');
    await page.screenshot({ path: path.join(os.tmpdir(), 'atelier-og-shared.png'), fullPage: true });
    await imageMode().selectOption('cover');
    await cardReady();
    assert.equal(await imageMode().inputValue(), 'cover');
    assert(await page.getByLabel('Размер текста', { exact: true }).isVisible(), 'Atelier can return from fallback to editable OG cover');
    assert.match(await page.locator('.studio-social-card img').getAttribute('src'), /^data:image\/png/);
    await page.getByLabel('Размер текста', { exact: true }).fill('94');
    await cardReady();
    await save();
    await page.reload();
    await cardReady();
    assert.equal(await imageMode().inputValue(), 'cover');
    assert.equal(await page.getByLabel('Размер текста', { exact: true }).inputValue(), '94');
    const atelierCover = await page.locator('.studio-social-card img').getAttribute('src');
    assert.deepEqual(Buffer.from(atelierCover.split(',')[1], 'base64'), await (await page.request.get(`${origin}/fabrics/aster-cucine/atelier/og-image`)).body());
    assert(!(await field('seo_image').isVisible()), 'Cover mode hides custom image picker');
    await page.screenshot({ path: path.join(os.tmpdir(), 'atelier-og-cover.png'), fullPage: true });
    console.log('Atelier mode switching, styling, save/reload and public image passed.');
    await page.goto(`${origin}/panel/pages/designers?tab=seo`);
    await cardReady();
    for (const name of ['seo_title', 'seo_description']) {
        assert(await textField(name).evaluate((input) => Boolean(input.labels?.length || input.getAttribute('aria-label') || input.getAttribute('aria-labelledby'))), `${name} needs an accessible label`);
    }
    assert.equal(await page.locator('.k-serp-section h3').innerText(), 'Дизайнерам | Студия Кухни');
    assert.match(await page.locator('.studio-sharing-preview').innerText(), /индексация отключена/);
    const beforeImage = await page.locator('.studio-social-card img').getAttribute('src');
    const title = 'Кухни для дизайнеров & архитекторов';
    const description = 'Помогаем подобрать кухню для проекта. Планировка, материалы и сопровождение.';
    await textField('seo_title').fill(title);
    await textField('seo_description').fill(description);
    await page.waitForFunction((expected) => document.querySelector('.k-serp-section h3')?.textContent.trim() === expected, `${title} | Студия Кухни`);
    assert.equal(await page.locator('.studio-social-card h3').innerText(), title);
    await cardReady();
    assert.notEqual(await page.locator('.studio-social-card img').getAttribute('src'), beforeImage);
    await save();
    await page.reload();
    await cardReady();
    assert.equal(await textField('seo_title').inputValue(), title);
    const publicPage = await browser.newPage();
    await publicPage.goto(`${origin}/designers`);
    assert.equal(await publicPage.title(), `${title} | Студия Кухни`);
    assert.equal(await publicPage.locator('meta[property="og:title"]').getAttribute('content'), title);
    assert.equal(await publicPage.locator('meta[name="description"]').getAttribute('content'), description);
    const ogUrl = await publicPage.locator('meta[property="og:image"]').getAttribute('content');
    const og = await page.request.get(ogUrl);
    assert.match(og.headers()['content-type'], /^image\/png(?:;|$)/);
    const bytes = await og.body();
    assert.equal(bytes.readUInt32BE(16), 1200);
    assert.equal(bytes.readUInt32BE(20), 630);
    const displayed = await page.locator('.studio-social-card img').getAttribute('src');
    assert.deepEqual(Buffer.from(displayed.split(',')[1], 'base64'), bytes);
    await publicPage.close();
    // Exercise the editor using the same controls available to page editors.
    await textField('seo_og_title').fill('Aster Cucine,\nAtelier');
    await cardReady();
    const size = page.getByLabel('Размер текста', { exact: true });
    await size.fill('88');
    await cardReady();
    const dragHandle = page.getByRole('button', { name: 'Положение текста:', exact: false });
    const box = await dragHandle.boundingBox();
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width / 2 + 12, box.y + box.height / 2 + 10, { steps: 5 });
    await page.mouse.up();
    await cardReady();
    const draggedX = await page.evaluate(() => Number(window.panel.content.version('changes').seo_og_x));
    assert(draggedX > 40, 'Dragging moves text horizontally');
    await dragHandle.focus();
    await page.keyboard.press('Shift+ArrowRight');
    await cardReady();
    assert.equal(await page.evaluate(() => Number(window.panel.content.version('changes').seo_og_x)), draggedX + 10);
    await save();
    await page.reload();
    await cardReady();
    assert.equal(await size.inputValue(), '88');
    assert.equal(await textField('seo_og_title').inputValue(), 'Aster Cucine,\nAtelier');
    const savedImage = await page.locator('.studio-social-card img').getAttribute('src');
    const adjustedResponse = await page.request.get(`${origin}/designers/og-image`);
    assert.deepEqual(Buffer.from(savedImage.split(',')[1], 'base64'), await adjustedResponse.body());
    const outputDir = process.env.STUDIO_SEO_SCREENSHOTS || temporary;
    fs.mkdirSync(outputDir, { recursive: true });
    await page.screenshot({ path: path.join(outputDir, 'og-editor-desktop.png'), fullPage: true });
    await page.getByRole('button', { name: 'Сбросить', exact: true }).click();
    await cardReady();
    assert.equal(await size.inputValue(), '112');
    assert.equal(await page.evaluate(() => Number(window.panel.content.version('changes').seo_og_x)), 40);
    await textField('seo_og_title').fill('');
    await cardReady();
    console.log('Cover text, font size, pointer drag, keyboard movement, reset and saved public pixels passed.');
    console.log('Live title, description, generated image, save/reload and public tags passed.');

    await imageMode().selectOption('shared');
    await cardReady();
    assert.match(await page.locator('.studio-social-card img').getAttribute('src'), /og-image_OG%20Fallback\.jpg$/);
    await save();
    const fallback = await page.request.get(`${origin}/designers/og-image`);
    assert.match(fallback.headers()['content-type'], /^image\/jpeg(?:;|$)/);
    assert.deepEqual(await fallback.body(), fs.readFileSync(path.join(root, 'assets/og/og-image_OG Fallback.jpg')));
    await imageMode().selectOption('custom');
    assert(!(await textField('seo_og_title').isVisible()), 'Custom image mode hides cover text');
    assert(!(await page.getByLabel('Размер текста', { exact: true }).isVisible()), 'Custom image mode hides cover styling');
    // Upload through Kirby's real file chooser and verify automatic/manual precedence.
    const chooser = page.waitForEvent('filechooser');
    await field('seo_image').getByRole('button', { name: 'Загрузить' }).click();
    await (await chooser).setFiles(path.join(root, 'assets/og/template.png'));
    await page.getByRole('dialog').getByRole('button', { name: 'Загрузить', exact: true }).click();
    await page.waitForFunction(() => window.panel.content.version('changes').seo_image?.[0]?.url && document.querySelector('.studio-social-card img')?.getAttribute('src') === window.panel.content.version('changes').seo_image[0].url);
    await cardReady();
    await imageMode().selectOption('cover');
    await page.waitForFunction(() => document.querySelector('.studio-social-card img')?.getAttribute('src').startsWith('data:'));
    await imageMode().selectOption('custom');
    await cardReady();
    assert.match(await page.locator('.studio-social-card img').getAttribute('src'), /template\.png$/);
    await imageMode().selectOption('shared');
    await cardReady();
    assert.match(await page.locator('.studio-social-card img').getAttribute('src'), /og-image_OG%20Fallback\.jpg$/);
    await imageMode().selectOption('cover');
    await cardReady();
    await field('seo_noindex').locator('input').check();
    assert.match(await page.locator('.studio-sharing-preview').innerText(), /Индексация запрещена настройкой/);
    await save();
    await page.reload();
    await cardReady();
    assert.equal(await imageMode().inputValue(), 'cover');
    assert(await field('seo_noindex').locator('input').isChecked());
    console.log('Image upload, explicit automatic cover and noindex persistence passed.');

    await page.goto(`${origin}/panel/site?tab=settings`);
    await cardReady();
    await textField('seo_title').fill('Студия современных кухонь');
    await textField('seo_description').fill('Общее описание для страниц сайта.');
    await page.waitForFunction(() => document.querySelector('.k-serp-section h3')?.textContent.includes('Главная | Студия современных кухонь'));
    assert.equal(await page.locator('.studio-social-card h3').innerText(), 'Главная');
    assert.equal(await page.getByRole('link', { name: 'Изменить заголовок и описание главной' }).getAttribute('href'), '/panel/pages/home?tab=seo');
    await save();
    await page.goto(`${origin}/panel/pages/faq?tab=seo`);
    await cardReady();
    assert.equal(await imageMode().inputValue(), 'cover', 'Untouched pages display automatic cover as enabled');
    assert(await textField('seo_og_title').isVisible(), 'Untouched pages can edit their cover text');
    assert.match(await page.locator('.studio-social-description').innerText(), /Общее описание/);
    assert.match(await page.locator('.studio-search-preview').innerText(), /Описание: из настроек сайта/);
    await textField('seo_title').fill('Длинныйзаголовокбезпробелов'.repeat(3));
    await cardReady();
    assert.match(await page.locator('.studio-search-preview').innerText(), /Может обрезаться/);
    await textField('seo_title').fill('');
    await cardReady();
    assert.match(await page.locator('.studio-search-preview').innerText(), /Заголовок: название страницы/);
    await size.fill('110');
    await cardReady();
    await save();
    await page.reload();
    await cardReady();
    assert.equal(await imageMode().inputValue(), 'cover', 'Saving untouched cover settings preserves automatic generation');
    const defaultImage = await page.locator('.studio-social-card img').getAttribute('src');
    assert.deepEqual(Buffer.from(defaultImage.split(',')[1], 'base64'), await (await page.request.get(`${origin}/faq/og-image`)).body());
    console.log('Site defaults, live inheritance, long text and clearing fields passed.');

    const output = process.env.STUDIO_SEO_SCREENSHOTS || temporary;
    fs.mkdirSync(output, { recursive: true });
    fs.writeFileSync(path.join(output, 'og-example.png'), bytes);
    await page.screenshot({ path: path.join(output, 'seo-desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForFunction(() => document.documentElement.scrollWidth <= innerWidth);
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile Panel must not overflow horizontally');
    await page.screenshot({ path: path.join(output, 'seo-mobile.png'), fullPage: true });
    await page.emulateMedia({ colorScheme: 'dark' });
    await page.waitForFunction(() => matchMedia('(prefers-color-scheme: dark)').matches);
    await page.screenshot({ path: path.join(output, 'seo-dark.png'), fullPage: true });
    for (const url of ['/archive/og-image', '/error/og-image', '/missing/og-image']) {
        assert.equal((await page.request.get(origin + url)).status(), 404);
    }
    assert.deepEqual(errors, [], 'Panel must not log runtime errors');
    assert.equal(fs.readdirSync(path.join(temporary, 'content/3_designers')).filter((name) => name.startsWith('generated-og-image')).length, 0);
    console.log('Mobile layout, dark theme, private routes and clean browser runtime passed.');
    await page.route('**/api/studio-seo/og-preview', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: 'null' }));
    await textField('seo_title').fill('Проверка восстановления обложки');
    await page.getByText('Не удалось создать обложку.', { exact: false }).waitFor();
    await page.unroute('**/api/studio-seo/og-preview');
    await page.getByRole('button', { name: 'Повторить', exact: true }).click();
    await cardReady();
    assert.equal(await page.getByText('Не удалось создать обложку.', { exact: false }).count(), 0);
    console.log('Failed image generation exposes retry and recovers without saving content.');
} catch (error) {
    if (editorPage) {
        await editorPage.screenshot({ path: path.join(os.tmpdir(), 'studio-seo-failure.png'), fullPage: true }).catch(() => {});
        console.error(await editorPage.locator('body').innerText().catch(() => ''));
        console.error(errors);
    }
    throw error;
} finally {
    await browser?.close();
    if (server && server.exitCode === null) {
        server.kill();
        await new Promise((resolve) => server.once('exit', resolve));
    }
    fs.rmSync(temporary, { recursive: true, force: true });
}
