server {
    listen 80;
    listen [::]:80;
    server_name studiya-kuhni-kmv.ru www.studiya-kuhni-kmv.ru xn-----flcfubncsg3bmne4a0n.xn--p1ai www.xn-----flcfubncsg3bmne4a0n.xn--p1ai;
    location ^~ /.well-known/acme-challenge/ { root /var/lib/letsencrypt; try_files $uri =404; }
    location / { return 301 https://studiya-kuhni-kmv.ru$request_uri; }
}
server {
    listen 80;
    listen [::]:80;
    server_name design.studiya-kuhni-kmv.ru;
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
    location ^~ /.well-known/acme-challenge/ { root /var/lib/letsencrypt; try_files $uri =404; }
    location / { return 301 https://design.studiya-kuhni-kmv.ru$request_uri; }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name studiya-kuhni-kmv.ru;
    ssl_certificate /etc/letsencrypt/live/studiya-kuhni-kmv.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/studiya-kuhni-kmv.ru/privkey.pem;
    root /srv/kuhni/notice/current;
    access_log /var/log/nginx/kuhni-notice-access.log;
    error_log /var/log/nginx/kuhni-notice-error.log;
    include /etc/nginx/snippets/kuhni-notice-app.conf;
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name www.studiya-kuhni-kmv.ru xn-----flcfubncsg3bmne4a0n.xn--p1ai www.xn-----flcfubncsg3bmne4a0n.xn--p1ai;
    ssl_certificate /etc/letsencrypt/live/studiya-kuhni-kmv.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/studiya-kuhni-kmv.ru/privkey.pem;
    return 301 https://studiya-kuhni-kmv.ru$request_uri;
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name design.studiya-kuhni-kmv.ru;
    ssl_certificate /etc/letsencrypt/live/design.studiya-kuhni-kmv.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/design.studiya-kuhni-kmv.ru/privkey.pem;
    root /srv/kuhni/design/current;
    access_log /var/log/nginx/kuhni-design-access.log;
    error_log /var/log/nginx/kuhni-design-error.log;
    include /etc/nginx/snippets/kuhni-design-app.conf;
}
