server {
    listen 80;
    listen [::]:80;
    server_name studiya-kuhni-kmv.ru www.studiya-kuhni-kmv.ru design.studiya-kuhni-kmv.ru xn-----flcfubncsg3bmne4a0n.xn--p1ai www.xn-----flcfubncsg3bmne4a0n.xn--p1ai;
    location ^~ /.well-known/acme-challenge/ {
        root /var/lib/letsencrypt;
        default_type text/plain;
        try_files $uri =404;
    }
    location / { return 503; }
}
